spring:
  datasource:   # H2 DB 설정
    url: jdbc:h2:mem:JPATest
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true   # H2 DB 웹콘솔 사용하도록 설정 (http://localhost:8080/h2-console)
  jpa:
    database: H2
    show-sql: true    # JPA 수행 시 SQL 문 로그로 출력
    properties:
      hibernate:
        format_sql: true    # 쿼리 출력 시 포맷 정렬되도록 설정
